# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled lakshita_jain28 e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective lakshita_jain28
ko_fi: gorvgoyl
tidelift: # Replace with a single Tidelift instagram/package-npm e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-cloud e.g., cloud-foundry
liberapay: # Replace with a single Liberapay lakshia_jain28
issuehunt: # Replace with a single IssueHunt lakshita_jain28
otechie: # Replace with a single Otechie lakshita_jain28    
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
